"""Static list of Malaysian public transit stations.

Sources: Wikipedia (Rapid KL, MRT Kajang Line, MRT Putrajaya Line, KTM Komuter).
Used to ground the GLM extractor so it can match station names in listing text.
"""

from __future__ import annotations

# fmt: off
STATIONS: list[dict] = [
    # ── LRT Kelana Jaya Line ────────────────────────────────────────────────
    {"name": "Gombak", "line": "LRT Kelana Jaya"},
    {"name": "Taman Melati", "line": "LRT Kelana Jaya"},
    {"name": "Wangsa Maju", "line": "LRT Kelana Jaya"},
    {"name": "Sri Rampai", "line": "LRT Kelana Jaya"},
    {"name": "Setiawangsa", "line": "LRT Kelana Jaya"},
    {"name": "Jelatek", "line": "LRT Kelana Jaya"},
    {"name": "Dato Keramat", "line": "LRT Kelana Jaya"},
    {"name": "Damai", "line": "LRT Kelana Jaya"},
    {"name": "KLCC", "line": "LRT Kelana Jaya"},
    {"name": "Titiwangsa", "line": "LRT Kelana Jaya"},
    {"name": "Chow Kit", "line": "LRT Kelana Jaya"},
    {"name": "Medan Tuanku", "line": "LRT Kelana Jaya"},
    {"name": "Sultan Ismail", "line": "LRT Kelana Jaya"},
    {"name": "Bandaraya", "line": "LRT Kelana Jaya"},
    {"name": "Bukit Nanas", "line": "LRT Kelana Jaya"},
    {"name": "Dang Wangi", "line": "LRT Kelana Jaya"},
    {"name": "Masjid Jamek", "line": "LRT Kelana Jaya"},
    {"name": "Raja Chulan", "line": "LRT Kelana Jaya"},
    {"name": "Bukit Bintang", "line": "LRT Kelana Jaya"},
    {"name": "Plaza Rakyat", "line": "LRT Kelana Jaya"},
    {"name": "Imbi", "line": "LRT Kelana Jaya"},
    {"name": "Hang Tuah", "line": "LRT Kelana Jaya"},
    {"name": "Pasar Seni", "line": "LRT Kelana Jaya"},
    {"name": "Kuala Lumpur", "line": "LRT Kelana Jaya"},
    {"name": "Maharajalela", "line": "LRT Kelana Jaya"},
    {"name": "Chan Sow Lin", "line": "LRT Kelana Jaya"},
    {"name": "Cheras", "line": "LRT Kelana Jaya"},
    {"name": "Miharja", "line": "LRT Kelana Jaya"},
    {"name": "Bandar Tun Razak", "line": "LRT Kelana Jaya"},
    {"name": "Pandan Jaya", "line": "LRT Kelana Jaya"},
    {"name": "Bangsar", "line": "LRT Kelana Jaya"},
    {"name": "Abdullah Hukum", "line": "LRT Kelana Jaya"},
    {"name": "Universiti", "line": "LRT Kelana Jaya"},
    {"name": "Taman Jaya", "line": "LRT Kelana Jaya"},
    {"name": "Asia Jaya", "line": "LRT Kelana Jaya"},
    {"name": "Taman Bahagia", "line": "LRT Kelana Jaya"},
    {"name": "Ara Damansara", "line": "LRT Kelana Jaya"},
    {"name": "Lembah Subang", "line": "LRT Kelana Jaya"},
    {"name": "Glenmarie", "line": "LRT Kelana Jaya"},
    {"name": "Subang Jaya", "line": "LRT Kelana Jaya"},
    {"name": "Kelana Jaya", "line": "LRT Kelana Jaya"},
    {"name": "Putra Heights", "line": "LRT Kelana Jaya"},

    # ── LRT Ampang / Sri Petaling Line ─────────────────────────────────────
    {"name": "Sentul Timur", "line": "LRT Ampang"},
    {"name": "Sentul", "line": "LRT Ampang"},
    {"name": "Titiwangsa", "line": "LRT Ampang"},
    {"name": "PWTC", "line": "LRT Ampang"},
    {"name": "Sultan Ismail", "line": "LRT Ampang"},
    {"name": "Bandaraya", "line": "LRT Ampang"},
    {"name": "Masjid Jamek", "line": "LRT Ampang"},
    {"name": "Chan Sow Lin", "line": "LRT Ampang"},
    {"name": "Ampang Park", "line": "LRT Ampang"},
    {"name": "KLCC", "line": "LRT Ampang"},
    {"name": "Ampang", "line": "LRT Ampang"},
    {"name": "Pandan Indah", "line": "LRT Sri Petaling"},
    {"name": "Pandan Jaya", "line": "LRT Sri Petaling"},
    {"name": "Maluri", "line": "LRT Sri Petaling"},
    {"name": "Miharja", "line": "LRT Sri Petaling"},
    {"name": "Cempaka", "line": "LRT Sri Petaling"},
    {"name": "Salak Selatan", "line": "LRT Sri Petaling"},
    {"name": "Sungai Besi", "line": "LRT Sri Petaling"},
    {"name": "Bandar Tun Hussein Onn", "line": "LRT Sri Petaling"},
    {"name": "Bukit Jalil", "line": "LRT Sri Petaling"},
    {"name": "Sri Petaling", "line": "LRT Sri Petaling"},
    {"name": "Awan Besar", "line": "LRT Sri Petaling"},
    {"name": "Muhibbah", "line": "LRT Sri Petaling"},
    {"name": "Alam Sutera", "line": "LRT Sri Petaling"},
    {"name": "Kinrara BK5", "line": "LRT Sri Petaling"},
    {"name": "IOI Puchong Jaya", "line": "LRT Sri Petaling"},
    {"name": "Pusat Bandar Puchong", "line": "LRT Sri Petaling"},
    {"name": "Puchong Prima", "line": "LRT Sri Petaling"},
    {"name": "Puchong Perdana", "line": "LRT Sri Petaling"},
    {"name": "Putra Heights", "line": "LRT Sri Petaling"},
    {"name": "Cahaya", "line": "LRT Sri Petaling"},

    # ── MRT Kajang Line ─────────────────────────────────────────────────────
    {"name": "Kwasa Damansara", "line": "MRT Kajang"},
    {"name": "Kwasa Sentral", "line": "MRT Kajang"},
    {"name": "Kota Damansara", "line": "MRT Kajang"},
    {"name": "Surian", "line": "MRT Kajang"},
    {"name": "Mutiara Damansara", "line": "MRT Kajang"},
    {"name": "Bandar Utama", "line": "MRT Kajang"},
    {"name": "Taman Tun Dr Ismail", "line": "MRT Kajang"},
    {"name": "TTDI", "line": "MRT Kajang"},
    {"name": "Phileo Damansara", "line": "MRT Kajang"},
    {"name": "Pavilion Damansara Heights", "line": "MRT Kajang"},
    {"name": "Pusat Bandar Damansara", "line": "MRT Kajang"},
    {"name": "Semantan", "line": "MRT Kajang"},
    {"name": "Muzium Negara", "line": "MRT Kajang"},
    {"name": "Pasar Seni", "line": "MRT Kajang"},
    {"name": "Merdeka", "line": "MRT Kajang"},
    {"name": "Bukit Bintang", "line": "MRT Kajang"},
    {"name": "Tun Razak Exchange", "line": "MRT Kajang"},
    {"name": "TRX", "line": "MRT Kajang"},
    {"name": "Cochrane", "line": "MRT Kajang"},
    {"name": "Maluri", "line": "MRT Kajang"},
    {"name": "Taman Pertama", "line": "MRT Kajang"},
    {"name": "Taman Midah", "line": "MRT Kajang"},
    {"name": "Taman Mutiara", "line": "MRT Kajang"},
    {"name": "Taman Connaught", "line": "MRT Kajang"},
    {"name": "Taman Suntex", "line": "MRT Kajang"},
    {"name": "Sri Raya", "line": "MRT Kajang"},
    {"name": "Bandar Tun Hussein Onn", "line": "MRT Kajang"},
    {"name": "Batu 11 Cheras", "line": "MRT Kajang"},
    {"name": "Bukit Dukung", "line": "MRT Kajang"},
    {"name": "Sungai Jernih", "line": "MRT Kajang"},
    {"name": "Stadium Kajang", "line": "MRT Kajang"},
    {"name": "Kajang", "line": "MRT Kajang"},

    # ── MRT Putrajaya Line ──────────────────────────────────────────────────
    {"name": "Sungai Buloh", "line": "MRT Putrajaya"},
    {"name": "Damansara Damai", "line": "MRT Putrajaya"},
    {"name": "Sri Damansara Barat", "line": "MRT Putrajaya"},
    {"name": "Sri Damansara Sentral", "line": "MRT Putrajaya"},
    {"name": "Sri Damansara Timur", "line": "MRT Putrajaya"},
    {"name": "Metro Prima", "line": "MRT Putrajaya"},
    {"name": "Kepong Baru", "line": "MRT Putrajaya"},
    {"name": "Jinjang", "line": "MRT Putrajaya"},
    {"name": "Sri Delima", "line": "MRT Putrajaya"},
    {"name": "Kampung Batu", "line": "MRT Putrajaya"},
    {"name": "Kentonmen", "line": "MRT Putrajaya"},
    {"name": "Jalan Ipoh", "line": "MRT Putrajaya"},
    {"name": "Sentul Barat", "line": "MRT Putrajaya"},
    {"name": "Titiwangsa", "line": "MRT Putrajaya"},
    {"name": "Hospital Kuala Lumpur", "line": "MRT Putrajaya"},
    {"name": "Raja Uda", "line": "MRT Putrajaya"},
    {"name": "Ampang Park", "line": "MRT Putrajaya"},
    {"name": "Persiaran KLCC", "line": "MRT Putrajaya"},
    {"name": "Conlay", "line": "MRT Putrajaya"},
    {"name": "Tun Razak Exchange", "line": "MRT Putrajaya"},
    {"name": "Chan Sow Lin", "line": "MRT Putrajaya"},
    {"name": "Kuchai", "line": "MRT Putrajaya"},
    {"name": "Sungai Besi", "line": "MRT Putrajaya"},
    {"name": "Serdang Raya Utara", "line": "MRT Putrajaya"},
    {"name": "Serdang Raya Selatan", "line": "MRT Putrajaya"},
    {"name": "Serdang Jaya", "line": "MRT Putrajaya"},
    {"name": "UPM", "line": "MRT Putrajaya"},
    {"name": "Taman Equine", "line": "MRT Putrajaya"},
    {"name": "Putra Permai", "line": "MRT Putrajaya"},
    {"name": "16 Sierra", "line": "MRT Putrajaya"},
    {"name": "Cyberjaya Utara", "line": "MRT Putrajaya"},
    {"name": "Cyberjaya City Centre", "line": "MRT Putrajaya"},
    {"name": "Putrajaya Sentral", "line": "MRT Putrajaya"},

    # ── KL Monorail ─────────────────────────────────────────────────────────
    {"name": "KL Sentral", "line": "Monorail"},
    {"name": "Tun Sambanthan", "line": "Monorail"},
    {"name": "Maharajalela", "line": "Monorail"},
    {"name": "Hang Tuah", "line": "Monorail"},
    {"name": "Imbi", "line": "Monorail"},
    {"name": "Bukit Bintang", "line": "Monorail"},
    {"name": "Raja Chulan", "line": "Monorail"},
    {"name": "Bukit Nanas", "line": "Monorail"},
    {"name": "Medan Tuanku", "line": "Monorail"},
    {"name": "Chow Kit", "line": "Monorail"},
    {"name": "Titiwangsa", "line": "Monorail"},

    # ── BRT Sunway ──────────────────────────────────────────────────────────
    {"name": "Sunway-Setia Jaya", "line": "BRT Sunway"},
    {"name": "Bandar Puteri", "line": "BRT Sunway"},
    {"name": "Taipan", "line": "BRT Sunway"},
    {"name": "Puchong Perdana", "line": "BRT Sunway"},
    {"name": "Wawasan", "line": "BRT Sunway"},
    {"name": "Puchong Prima", "line": "BRT Sunway"},
    {"name": "USJ 7", "line": "BRT Sunway"},

    # ── KTM Komuter ─────────────────────────────────────────────────────────
    {"name": "Batu Caves", "line": "KTM"},
    {"name": "Batu Kentonmen", "line": "KTM"},
    {"name": "Kampung Batu", "line": "KTM"},
    {"name": "Taman Wahyu", "line": "KTM"},
    {"name": "Sentul", "line": "KTM"},
    {"name": "Bank Negara", "line": "KTM"},
    {"name": "Kuala Lumpur", "line": "KTM"},
    {"name": "KL Sentral", "line": "KTM"},
    {"name": "Angkasapuri", "line": "KTM"},
    {"name": "Mid Valley", "line": "KTM"},
    {"name": "Seputeh", "line": "KTM"},
    {"name": "Salak Selatan", "line": "KTM"},
    {"name": "Serdang", "line": "KTM"},
    {"name": "Kajang", "line": "KTM"},
    {"name": "UKM", "line": "KTM"},
    {"name": "Putra", "line": "KTM"},
    {"name": "Nilai", "line": "KTM"},
    {"name": "Labu", "line": "KTM"},
    {"name": "Tiroi", "line": "KTM"},
    {"name": "Seremban", "line": "KTM"},
    {"name": "Senawang", "line": "KTM"},
    {"name": "Sungai Gadut", "line": "KTM"},
    {"name": "Rembau", "line": "KTM"},
    {"name": "Pulau Sebang", "line": "KTM"},
    {"name": "Tanjung Malim", "line": "KTM"},
    {"name": "Rasa", "line": "KTM"},
    {"name": "Serendah", "line": "KTM"},
    {"name": "Batang Kali", "line": "KTM"},
    {"name": "Kuala Kubu Bharu", "line": "KTM"},
    {"name": "Rawang", "line": "KTM"},
    {"name": "Sungai Buloh", "line": "KTM"},
    {"name": "Kepong Sentral", "line": "KTM"},
    {"name": "Kepong", "line": "KTM"},
    {"name": "Segambut", "line": "KTM"},
    {"name": "Subang Jaya", "line": "KTM"},
    {"name": "Shah Alam", "line": "KTM"},
    {"name": "Batu Tiga", "line": "KTM"},
    {"name": "Klang", "line": "KTM"},
    {"name": "Teluk Pulai", "line": "KTM"},
    {"name": "Teluk Gadong", "line": "KTM"},
    {"name": "Kampung Raja Uda", "line": "KTM"},
    {"name": "Jeram", "line": "KTM"},
    {"name": "Bukit Badak", "line": "KTM"},
    {"name": "Port Klang", "line": "KTM"},
    {"name": "Terminal Skypark", "line": "KTM"},
]
# fmt: on


def build_station_reference() -> str:
    """Return a compact station list string for injection into GLM prompts."""
    by_line: dict[str, list[str]] = {}
    for s in STATIONS:
        by_line.setdefault(s["line"], []).append(s["name"])

    lines = []
    for line, names in by_line.items():
        lines.append(f"{line}: {', '.join(names)}")
    return "\n".join(lines)
